ct-app/economic_handler/economic_handler.py, ct-app/requirements.txt, ct-app/tests/test_hoprd_api_helper.py, ct-app/tests/test_hoprd_bad_api_helper.py, ct-app/tests/test_netwatcher.py, ct-app/tests/test_other_endpoints.py, ct-app/tools/hopr_api_helper.py
This PR is on the transition from the old API structure (handwritten) to the new one (generated by Swagger). It is still not using the API for MR2.0 as it is not released yet.
Only the `HoprdApiHelper` is directly affected by the changes in the API structure. However, some minor changes were required in order to conform to new parameters, and so that the tests still pass (for instance, exception raised are different).
Resolves #220
=> Switch to new hoprd api structure

ct-app/economic_handler/economic_handler.py, ct-app/netwatcher/netwatcher.py
This PR closes the interrogation we had on "what is the best way to interrupt a long running task". The implementation relies on this [wiki-page](https://github.com/hoprnet/ct-research/wiki/Handling-of-task-interruption), and further more on how the `asyncio` library is dealing with task interruption.
=> Async long running tasks now interrupted the right way

ct-app/aggregator/aggregator.py, ct-app/aggregator/routes.py, ct-app/aggregator/setup.py, ct-app/aggregator/utils.py, ct-app/netwatcher/netwatcher.py, ct-app/requirements.txt, ct-app/tests/test_aggregator.py
Metrics are exposed at the `Aggregator` level through an http endpoint:`aggregator/metrics`. Those metrics are in the form of a .json file (dictionary). This is not Prometheus compatible. Prometheus requires that the metrics-endpoint returns data with a specific format.
Instead of simply returning a .json file, the metric-endpoint now returns the gathered metrics thanks to the `prometheus-client` library. This library allows to collect any data anywhere in the code, at any moment. When the metric-endpoint is called, the library gathers all the metrics stored and returns them with the desired format. 
Thus, a bunch of methods (and their corresponding test methods) have been removed, others simply adapted.
Please have a look at the Grafana dashboards for CT-app: …
=> Metrics now prometheus compatible

ct-app/economic_handler/__main__.py, ct-app/economic_handler/economic_handler.py, ct-app/tools/db_connection/database_connection.py, ct-app/tools/decorator.py
Changed the way the `econ_handler_decorator` is looking for the parameter file. Before, the file was located based on the `decorator.py` path, now it is based on the current folder where the module is executed from.
Also, the name of the decorator has been changed to not mention the `EconomicHandler`.
Resolves #205
=> EH decorator accessible by anyone

ct-app/postman/postman_tasks.py, ct-app/tools/hopr_api_helper.py
Until now, the `Postman` was trying to send a defined number of messages through a node. If the peer is available, send all the messages with this node, otherwise create a task for a different node. The problem is that even if the node is available to send the first messages, it can go down at any moment, and could not be able to send all the messages.
This PR adds a functionality to `Postman`: when sending X messages, it always checks for successful sending.
- if the sending succeeded &rarr; it tries to send the next message
- if the sending fail &rarr; it stops sending messages, and creates a task with the remaining message to send for the next node.
**Also added**
Now instead of looping through the node list until the last node, the task is looping indefinitely through this list. This …
=> Remaining messages now sent from next node in the list

.github/workflows/main.yaml, ct-app/aggregator/routes.py, ct-app/netwatcher/netwatcher.py, ct-app/tests/test_aggregator.py, ct-app/tests/test_db_connection.py, ct-app/tests/test_hoprd_api_helper.py, ct-app/tests/test_hoprd_bad_api_helper.py, ct-app/tests/test_netwatcher.py, ct-app/tools/hopr_api_helper.py, ct-app/tools/utils.py
Until now, `Netwatcher` was gathering peers every X minutes, and in the same time, pinging all of them in a sequential manner. Then every Y minutes, this latency list was sent to the `Aggregator`. Once the list was transfered, the gathered peers were forgotten, and everything was happening again.
This was inducing a strong constraint on timing, and the content of what was transmitted was not consistent: if a lot of peers where not pingable and the api-call was hitting the timeout, only a small amount of peers where added to the list that was transferred. 
In this PR, the behaviour of the `Netwatcher` gets closer to an asynchronous module: gathering peers is still done regularly, but the retrieve list of peers is never whipped out. Pinging peers is done by picking a random peers among all …
=> Sending list using a rolling strategy

ct-app/economic_handler/economic_handler.py
Resolves #270
This PR implements the apy calculation as part of the reward calculation function. The apy calculation is based on the `budget_period` parameter from the `parameters.json` file. The budget period is calculated in seconds. Therefore, the apy formula is as follows: 
`
apy = total_exp_reward * ((60 * 60 * 24 * 365) / budget_period_in_sec) / total_balance. 
` 
Important: `total_balance` is available once #277 gets merged. Therefore, I use `stake` for now. I will exchange this with a hotfix PR once everything is merged. 
Note that with a budget period defined a second a year has 60 * 60 * 24 * 365 seconds. This approach of calcualting the apy is robust to changes in the budget as budget changed will be reflected in the `total_expected_reward`. Furthermore, changes in the budget …
=> Added APY as part of the expected reward calculation

ct-app/economic_handler/__main__.py, ct-app/economic_handler/economic_handler.py, ct-app/tests/test_economic_handler.py, ct-app/tests/test_other_endpoints.py, ct-app/tests/test_utils_econhandler.py
Resolves #285
This PR implements the subgraph for rotsee and dufour. Note that the functionality of the subgraph is the same for both networks. The only difference is the subgraph url that must be passed as a secret. 
The subgraph creates the safe_address-node_address-balance link and the return dictionary is as follows, with the node_address as the key: 
```
{'0x78d294676bbd9030c6ff83899d4d42723a5ff71f': {'safe_address': '0x006936ee6fd2f05ef0230a8f87267ae31a1c2895', 'wxHOPR_balance': '10'}}
```
I choose the node_address to be the key as it is unique opposet to the safe_address which can be linked to multiple nodes in theory. Furthermore, this avoids duplicate entries by design and having the node_address as the key allows for a clean merge with the peer_id that can be obtained via the …
=> Subgraph Implementation

ct-app/requirements.txt
Python SDK v3 has been merged into the main branch of the python-sdk repo. This change needs to be reflected in the requirement file in this repo.
=> Using latest Python SDK (v3)

ct-app/aggregator/aggregator.py, ct-app/aggregator/routes.py, ct-app/aggregator_trigger/__main__.py, ct-app/aggregator_trigger/aggregator_trigger.py, ct-app/tests/test_aggregator_trigger.py
Until now, when a `Netwatcher` was not able to send anything to the `Aggregator`, the `Aggregator` would store infinitely not-up-to-date informations about the network. There is a mechanism at `Netwatcher` level to remove unpingable peers from the `Aggregator`, but this rely on the hypothesis that the `Netwatcher`-`Aggregator` communication is working.
Storing old information not updated could lead into sending rewards to someone not available, thus not eligible for rewards.
In this PR, a mechanism is added to the `Aggregator` to remove all informations about a given node, if this node has not been updated in the past 2h. This check is triggered by the `AggregatorTrigger` every 2minutes, and the last update for any node should never be older than 2h (same timedelta as the logic at the …
=> Remove all node measures when node is down

ct-app/tools/hopr_api_helper.py, ct-app/tools/utils.py
When doing request to the API, if an exception occured, the full traceback was printed by the `log.exception()` method. This was intentional. But actually, this full traceback is useful only to check the HTML response body. A lot of other lines were printed as logs, and were not helpful at all (origin of the error in the python wrapper for instance). 
In this PR, the HTML response body is manually extracted from the exception, and logged after the error message.
Also reduced the logging level to see even debug messages from the app.
=> Reduce logged traceback

ct-app/economic_handler/economic_handler.py
A control loop has been added in the EH before running the economic model. 
Basically, this loop controls that all the required ressources are available to run the economic model. If one of the 5 required resources (rpch nodes, ct nodes, subgraph data, topology data, database data), then the it loops back with a 5s delay to wait for those resources.
This loop avoids waiting for the next distribution if a resource in not available.
=> Control before running the economic model

ct-app/economic_handler/__main__.py, ct-app/economic_handler/economic_handler.py, ct-app/economic_handler/utils_econhandler.py
This PR adds a simple functionality that can be helpful for change the frequency distribution on the fly: instead of hardcoding the parameter file name, this one is provided trough an environment variable. This will be really helpful to continue developing and testing locally with a given set of parameters, and in the same time deploying the app with an other set of parameters.
Resolves #335
=> Using envvar to specify parameter file name

ct-app/economic_handler/__main__.py, ct-app/economic_handler/economic_handler.py, ct-app/tests/test_economic_handler.py, ct-app/tests/test_other_endpoints.py
This PR adds a functionality that avoid running the economic model and doing the distribution if the number of retrieved entries in the database is too low.
The threshold has the be set by an environment variable called `MIN_DATABASE_ENTRIES`. The recommended value is 100.
Resolves #313
=> Logic to block economic model if database not filled enough

ct-app/economic_handler/economic_handler.py, ct-app/economic_handler/utils_econhandler.py, ct-app/tests/test_economic_handler.py, ct-app/tools/decorator.py
On `EconomicHandler` instance start, a distribution is automatically executed. If the pod crashes on production, it is automatically being restarted, thus triggering a distribution. This is an undesired situation.
In this PR, the triggering of the distribution is done by the `wakeupcall` decorator instead of `wakeupcall_from_file`. The latter was not waiting for the right time to start, but way directly executing the decorating method, and then sleeps. The `wakeupcall` decorator sleep first until the right time, then execution the method, and sleeps again for the desired amount of time.
Resolves #347
=> Using `wakeupcall` instead of `wakeupcall_from_file`

.gitignore, ct-app/postman/postman_tasks.py
This PR makes the Postman's `fake_task` more "complex". Instead of simply writing messages in the logs, it now creates a task for the feedback queue, that should then store informations in the reward table of the database
=> Fake task write in rewardTable

ct-app/economic_handler/__main__.py, ct-app/economic_handler/economic_handler.py, ct-app/tests/test_economic_handler.py, ct-app/tests/test_other_endpoints.py
This PR splits the reward calculation and sending.
It allows a simpler threshold definition: before, a threshold was set on the database entries count. If there was enough data in the latest push, the economic model would have been triggered (considering all other informations sources available). But this could lead to an empty merged result dataset.
Now that the sending is splitted, the threshold is set on the number of eligible peers just before sending rewards.
The calculation of eligible peers is done every 2min, where the sending of rewards is done every ~7h (based on the economic model).
In this PR, a the environment variable `MIN_DATABASE_ENTRIES` changed to `MIN_ELIGIBLE_PEERS`.
=> Reward calculation and sending splitted

ct-app/netwatcher/netwatcher.py, ct-app/tests/test_netwatcher.py
This PR modifies the logic with which the NW opens channels. Before, it was only opening channels to peers that were missing a channel from a NW. Now, the NW still opens required channels, but also closes the ones in which only a few tokens remains.
=> Closing channels with low balance

ct-app/postman/postman_tasks.py, ct-app/tests/test_postman.py, ct-app/tools/db_connection/models.py
A message is considered "issued" when the `api.send_message` call return a positive response. Among all the message we are expected to send, the majority of them are issued (can be not all), and some of the issued message are received back.
Storing this metric in the database will help understand what is failing where about reward distribution.
=> Storing issued messages in the rewardTable

ct-app/__airdrop__/__init__.py, ct-app/__airdrop__/__main__.py, ct-app/__airdrop__/gcpfile.py, ct-app/__airdrop__/reward_entry.py, ct-app/__airdrop__/table_entry.py
This PR adds a module called `__airdrop__` that is able to aggregate informations from multiple csv's stored on GCP. The result is printed in the console in a .csv format
The usage is the following
```bash
Usage: python -m __airdrop__ [OPTIONS]
Options:
--start TEXT   Start date, inclusive (YYYYMMDD-HHMMSS
format)
--end TEXT     End date, exclusive (YYYYMMDD-HHMMSS format)
--bucket TEXT  GCP bucket name
--folder TEXT  Folder name inside bucket
--help         Show this message and exit.
```
If it is used with the following command: 
```bash
python -m __airdrop__ --start <start-date> --end <end-date>
```
the bucket and folder will be set to some default values, already pointing to the directory where ct is storing reward calculations.
If the result needs to be stored as a .csv file, simply …
=> Script to generate an airdrop csv

ct-app/aggregator/routes.py, ct-app/tools/__init__.py, ct-app/tools/logger/coloredformatter.py, ct-app/tools/logger/coloredlogger.py, ct-app/tools/utils.py
This PR changes the way logs are printed:
- timestamp are not shown in the log line anymore: as Loki is retrieving the time at which a log is printed, the time information was available twice in a log line (see grafana dashboards), which could lead in some confusions due to the usage of different timezones between Loki and the application itself.
- Colors are used with the debug/info/warning/error keywords to outline more clearly what kind of content is in the log line
- The running module tag has been removed from line, as this information can be infered from the running module in Loki/Grafana
- Unnecessary characters have been removed to avoid filling a line with format.
```log
[2023-11-06 10:23:53][RUNNING_MODULE][DEBUG/INFO/WARNING/ERROR] Dummy message in the log.
```
```log …
```
=> Logging simplification

ct-app/postman/postman_tasks.py, ct-app/tests/test_postman.py
Hotfix for channel retrieval. The postman needs to detect the balance of the channel between itself and a node. This is done through the api, but the api call that was done before (`get channels/outgoing/`) has to issues:
- retrieving destination address was not possible
- retrieving balance was not possible
The api call is now changed to `get channels` and manual filtering is done to get the correct channel, thus channel balance.
=> Channel's filter conditions where off in Postman 

.gitignore, ct-app/core/__main__.py, ct-app/core/components/baseclass.py, ct-app/core/components/decorators.py, ct-app/core/components/flags.py, ct-app/core/components/parameters.py, ct-app/core/components/utils.py, ct-app/core/core.py, ct-app/core/node.py, ct-app/get_params.sh, ct-app/namtsop/namtsop_tasks.py, ct-app/postman/postman_tasks.py, ct-app/scripts/list_required_parameters.sh, ct-app/test/components/test_decorators.py
CT v2.* heavily relies on environment variables. Those variables are used are either optional flags or mandatory parameters. 
On runtime, a parser goes through the specified environment variables and create a parameter object containing all environment values that match a given pattern (`PARAM_` + `<category>` + `<var_name>`). 
This automatic parsing allows the developer to add some parameters in the code by accessing them through the dynamically created parameter instance, without prior checks. This way to deal with environment variable is nice, but also has a great drawback: a given variable may not be available in the environment, and the app would only now it is missing on runtime. 
This PR adds a prior check, still on runtime but at the very start of any module, that all the required …
=> Runtime check that env variables are set before using them

ct-app/core/__main__.py, ct-app/core/core.py, ct-app/core/model/peer.py, ct-app/core/model/topology_entry.py, ct-app/core/node.py, ct-app/test/components/test_utils.py, ct-app/test/model/test_peer.py
To incentivize peers to update their nodes to a recent version, CT will distribute rewards only to peers running on a given version or higher. 
The minimum version is to be set by an environment variable as a string in this way: 
`export PEER_MIN_VERSION="2.0.0-rc.1"`
Any peer running on the same or a more recent rc or release than the minimum version will receive CT.
=> Exclude peers running on old version

ct-app/core/components/hoprd_api.py, ct-app/core/node.py
API was fed with an int instead of a string
=> Fixed funding amounts

ct-app/core/components/utils.py, ct-app/core/core.py
A subgraph endpoint rotation is done between the centralized and decentralized (used by default) in case one or the other is failing to return data.
Until now, we were only checking that the endpoint returns something (it happens that the endpoint is even not reachable) but this is not enough. In case a error is thrown by the server, it will be counted as a successful response, which would not trigger the rotation. 
Now, when check an endpoint, a check that the result structure is correct is done. This will force the rotation on error thrown.
=> Update check_subgraph_urls to handle empty response data

ct-app/core/core.py, ct-app/core/model/peer.py
This PR allows to limit the APR to any given value, defined as the environment variable `DISTRIBUTION_MAX_APR_PERCENTAGE`.
A small restructuration of the `Peer` class was need. The total expected reward property was used to compute airdrop reward amount, protocol reward amount, and APR. Thus limiting the APR would not have changed the amount distributed through the protocol. 
Now, the expected reward property is used to compute the APR, which is used to compute the airdrop and protocol reward amount.
Resolves #453
=> Limit APR with environment variable

ct-app/core/components/utils.py, ct-app/core/model/peer.py
Before, checking that a node was eligible was done by computing this:
```python
all([
self.address,
self.channel_balance,
self.safe_address,
self.safe_balance,
self.safe_allowance,
])
```
which could be wrong if any of the values were equal to `0`.
However, on this step we only need to know if the values were set to something different than `None`. This has been changed in this PR.
=> Fixing node eligibility

ct-app/core/core.py, ct-app/core/node.py
CT Core relies on nodes, more precisely on node's API's. In case a node get unreachable, a call to it's API will fail. This behaviour is expected, but needs some attention. 
If a result of the API call is a dictionary, accessing the content of this dictionary needs to be done in a safe way.
This was done most of the time, but some remaining parts of the codes were still using API results without checking that the result is indeed available.
This PR fixes this issue (#459)
=> Fix core too strongly bound to underlying nodes

ct-app/core/components/hoprd_api.py, ct-app/requirements.txt
With the previous implementation, `HoprdAPI` was using the token provided on the instantiation of the last instance for all instances.
A workaround is to update the token with a hook at each call, to be sure that for every node, the correct credentials are used.
=> Fix `HoprdAPI` token handling

ct-app/core/components/utils.py, ct-app/core/model/topology_entry.py, ct-app/test/model/test_peer.py
Version (`0.0.0`) was set in the topology class as default, waiting for an update from the peer list when merging data sources. This update wasn't done, thus all peers appeared to be running on `0.0.0` instead of the real node version.
=> Peer version not propagated when merging data sources

ct-app/scripts/core_prod_config.yaml
As the ticket price shall increase back again, the distribution needs to be triggered less often again. This PR sets distributions every 30min.
=> Set slower distribution rate

ct-app/core/api/hoprd_api.py, ct-app/core/core.py
All balances on the 2.3 compliant CT version are in wei. Thus, in the dashboard, for readability, balances are divided by 1e18.
However, in the 3.0 compliant CT version, all balances are in wxHOPR. In the dashboards, dividing currencies by 1e18 wouldn't make sense anymore. 
The added metric allows to dynamically do the conversion.
It will be removed once a single CT instance will run, for 3.0 nodes. 
Twin PR for 2.3: #678
=> Expose balance multiplier (3.0)
