hoprnet/ct-research

ct-app/assets/parameters.json
ct-app/assets/parameters_schema.py
ct-app/economic_handler/economic_handler.py
ct-app/tests/test_economic_handler.py
ct-app/tools/hopr_api_helper.py
ct-app/tools/utils.py

Resolves #219 
This PR adds the `winning_probability` and the `ticket_price` to the `parameters.json` file as the parameters define the number of   messages that must be sent according to the following formula: `messages = protocol_exp_reward_per_dist / (ticket_price * winning_probability)`. Note that messages are called `jobs` in the code.  Furthermore, note that the `winning_probability` of a ticket is hardcoded into hoprd and, therfore, cannot be changed at runtime. Instead, a new release must be cut which gives us enough time to adapt this value in the `parameters.json` file accordingly. However, `ticket_price` can be changed at runtime through the ticket price oracale (this is a smart contract) to react to changes in the hopr token price. As the HOPR Association controls this smart …

Queue communication and task distribution

---

ct-app/aggregator_trigger/aggregator_trigger.py

Everything is in the PR title.
Resolves #240

AggTrigger wakes up every 2h

---

ct-app/postman/postman_tasks.py
ct-app/tools/hopr_api_helper.py

236 send remaining messages from next node in the list

---

ct-app/tools/logger/coloredformatter.py
ct-app/tools/logger/coloredlogger.py

Logger now prints the current datetime

---

ct-app/aggregator/routes.py
ct-app/tools/db_connection/database_connection.py

Each time `Aggregator` has to push data to the database table, multiple entries are pushed. Until now, entries were pushed one by one, inducing a different timestamp for each entry.
This PR uses the `insert_many` method of the `DatabaseConnection` class to push multiple entries at the same time.
Resolves #243

Inserting data to db as a block

---

ct-app/aggregator/routes.py
ct-app/economic_handler/economic_handler.py
ct-app/tests/test_db_connection.py
ct-app/tools/db_connection/database_connection.py

Table name as attribute of DatabaseConnection

---

ct-app/netwatcher/netwatcher.py

Peer list replaced instead of updated

---

ct-app/netwatcher/netwatcher.py
ct-app/tools/hopr_api_helper.py

Peer quality reduced

---

ct-app/postman/__init__.py
ct-app/postman/postman_tasks.py
ct-app/tests/test_postman.py
ct-app/tools/hopr_api_helper.py
ct-app/tools/utils.py

Added unittests and corrected exception handling

246 2 add test cases for postman

---

ct-app/economic_handler/economic_handler.py

Resolves #209
This PR implements a function that blocks `ct-app` nodes from the ct reward distribution. In particular, it blocks nodes associated with the `Netwatcher` and `Postman` module. To block the node addresses, I use the list of netwatcher nodes associated with a given peer in the network. 
Importantly, the function does not exclude the node associated with the `economic_handler` module itself from the rewards distribution. However, as the `economic_handler` node does not open any outgoing payment channels the node will be automatically exculded. The reason is that we only consider nodes for distribution that have at least 1 open payment channel. 
Test of the function. Due to expected changes in the data structure this task will be done as part of #211

Block ct nodes from reward distribution

---

.gitignore
ct-app/tests/test_db_connection.py
ct-app/tools/db_connection/database_connection.py
ct-app/tools/db_connection/models.py

In this PR, I simplified the code of `DatabaseConnection` to remove unnecessary parts.
As well, the DatabaseConnection test file has been removed as nothing else than connection remains in the class.

Database connection hot fix

---

ct-app/requirements.txt

Added missing requirement for sqlAlchemy to be able to communicate with database.

added psycopg2 requirement

---

ct-app/netwatcher/netwatcher.py
ct-app/tools/hopr_api_helper.py

corrected bug on vanishing peer logic and peer selection for agg-transmission

---

ct-app/economic_handler/economic_handler.py

Resolves #176
Adds logging information to the economic handler and removes traceback.

improve logging in econ handler

---

ct-app/postman_feedback/postman_feedback_task.py

Adapt PF to match the DatabaseConnection implementation

---

.github/workflows/main.yaml
ct-app/economic_handler/economic_handler.py
ct-app/economic_handler/utils_econhandler.py
ct-app/requirements.txt
ct-app/tests/test_utils_econhandler.py
ct-app/tools/__init__.py
ct-app/tools/decorator.py
ct-app/tools/utils.py

Until now, generated csv files were saved locally, and parameter file were read locally too. In staging/production, this wouldn't have worked. Instead, in this PR, files are read and written to a GCP bucket.

Saving and reading files to/from GCP bucket

---

ct-app/economic_handler/economic_handler.py

The previous refactoring (see PR #284) introduced some potentials concurrency issues. Those have been resolved in this PR by using thread locks. Everytime that a variable is used but its state could be modified/used somewhere else at the same, a lock has been added to wait for the variable to be available.
Locks has not been added at the beginning of the `apply_economic_model` method (when checking if variable have been set at least once), because here the content is not relevant, we only check if *there is* something stored.

Added locks to avoid concurrency issues in EH

---

ct-app/economic_handler/utils_econhandler.py
ct-app/tests/test_other_endpoints.py
ct-app/tests/test_utils_econhandler.py

Fix the test in the economic handler and bug fixes in the economic handler discovered by the tests.

Unittest for econ handler and bug fixes based on tests 

---

ct-app/economic_handler/__main__.py
ct-app/economic_handler/economic_handler.py
ct-app/postman/postman_tasks.py
ct-app/tests/test_economic_handler.py
ct-app/tests/test_other_endpoints.py

PR adds an infomrative message to message-distribution

Change message on distribution

---

ct-app/postman_feedback/postman_feedback_task.py

Fixed the type of the timestamp pushed to rewardTable

---

ct-app/economic_handler/economic_handler.py
ct-app/tests/test_other_endpoints.py

Resolves #333 
1) The query returns now only the set of elidgible nodes for network rewards. 
2) Fixed the unit tests

fixed get subgraph method and unittests

---

ct-app/aggregator_trigger/aggregator_trigger.py
ct-app/economic_handler/economic_handler.py
ct-app/netwatcher/__main__.py
ct-app/netwatcher/netwatcher.py
ct-app/tests/test_economic_handler.py
ct-app/tests/test_other_endpoints.py

This PR is the final PR before starting distribution to the community.
Once all the necessary modifications are added to the code, take the last hash and use it as tag for the applications file in this [ct-application PR #17](https://github.com/hoprnet/ct-applications/pull/17)

Final modifications before release

---

ct-app/netwatcher/netwatcher.py

Safe balances gathered by Netwatchers

---

ct-app/economic_handler/utils_econhandler.py
ct-app/postman/postman_tasks.py
ct-app/tests/test_postman.py

In this PR, a channel balance check is done before sending messages. If the balance is too low, only a subset of messages worth the channel balance are sent.

Balance check done before sending messages

---

.gitignore
ct-app/core/components/utils.py
ct-app/core/ctcore.py

Subgraph endpoint rotation added

---

ct-app/netwatcher/netwatcher.py

App do not close channels anymore

---

.gitignore
ct-app/metrics/relayed_token.ipynb

This PR computes a metric about the token relayed by the `ct-app`. There is a lot of room for improvement of this metric. In the best case this metric can be exposed out of the box by grafana in the future.

Relayed token metric

---

waitlist/dune_entry.py
waitlist/entry.py

Add node_address field on DuneEntry import/export

---

ct-app/core/components/utils.py

Fix missing argument in SubgraphEntry

---

ct-app/README.md

Specified required parameters in README.md and updated running instructions

README update to match v2

---

ct-app/postman/postman_tasks.py
ct-app/postman/task_status.py

Fix stored expected count

---

ct-app/core/node.py

Low balance calculation was off by a factor 1e18... actually comparing tokens to wei..

Fix low balance calculation in Node class

---

ct-app/core/core.py

Adding a metric to track peer ID versions

Track peer versions

---

ct-app/core/node.py

ctdapp relies a lot on the hoprd nodes' API. Two of the calls done regularly are to get all incoming and outgoing channels. The call done returns an object with the following structure: 
```json
{
"incoming": [ ],
"outgoing": [ ],
"all": [ ],
}
```
There was a missing check before accessing the result, which could lead into a crash if the desired key (`incoming`, `outgoing` or `all`) wasn't in the response -- which could be the case when the API call fails.
This has been fixed in this PR. An additional check has been added when accessing the node's peerID (same kind of issue as the one describe up-above, only translated to another API call).
This should prevent ctdapp to crash when the node died unexpectedly.

Fix generated class usage without content checks

---

helm/ctdapp/templates/secret-rabbitmq.yaml

Fix typo in namespace
